from ._loader import load_raw_texts_as_sentences
from ._loader import load_raw_spoken_text_as_sentences
from ._loader import load_raw_written_text_as_sentences
from ._loader import load_raw_texts_as_morphemes_sentences
from ._loader import load_raw_texts_as_eojeol_table