from ._loader import load_texts_as_eojeol_morphemes
from ._loader import load_spoken_text_as_eojeol_morphemes
from ._loader import load_written_text_as_eojeol_morphemes
from ._loader import load_texts_as_corpus
from ._loader import load_texts_as_eojeol_morphemes_table