from .utils import check_encoding
from .utils import load_texts_as_sentences
from .utils import load_spoken_text_as_sentences
from .utils import load_written_text_as_sentences
from .utils import load_as_morphemes_sentences
from .utils import load_as_eojeol_table
from .utils import write_sentences
from .utils import Corpus
from .statistics import count_tags
from .statistics import count_tag_words
from .simplify import tagmap
from .simplify import simplify_tag